import Navbar from "@/components/navbar"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: {
    default: "Next.js",
    template:"%s | byRobz"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <p>Header</p>
        </header>
        <nav>
        <Navbar/>
        </nav>
          {children}
        <footer>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  )
}
